"""Constants for the Siku RV Fan integration."""

DOMAIN = "siku"
DEFAULT_MANUFACTURER = "Siku"
DEFAULT_MODEL = "RV"
DEFAULT_NAME = "Fan"
DEFAULT_PORT = 4000

CONF_VERSION = "version"
CONF_ID = "idnum"

FAN_SPEEDS = ["01", "02", "03"]
DIRECTION_FORWARD = "00"
DIRECTION_ALTERNATING = "01"
DIRECTION_REVERSE = "02"
DIRECTIONS = {
    DIRECTION_FORWARD: "forward",
    DIRECTION_ALTERNATING: "alternating",
    DIRECTION_REVERSE: "reverse",
}
