#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

# Install packages
apt-get update
apt-get install -y libpcap-dev ffmpeg

# Install dependencies
python3 -m pip install --requirement requirements.txt
